# Pre-commit configuration file
# For more information, refer to https://pre-commit.com

repos:
  # Common pre-commit hooks to maintain code quality
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.30
    hooks:
      - id: terragrunt-hcl-fmt
        files: \.hcl$

  # Terraform specific hooks for code quality and documentation
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.98.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        args:
          - --args=--config=.terraform-docs.yaml
      - id: terraform_trivy
        args:
          - --args=--config=__GIT_WORKING_DIR__/trivy.yaml
          - --args=--ignorefile=__GIT_WORKING_DIR__/.trivyignore
          - --args=--skip-dirs=.terraform
      - id: terraform_tflint
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
          - --args=--init

  # - repo: local
  #   hooks:
  #     - id: Infracost
  #       name: Infracost Html Report
  #       entry: make cost-ci
  #       require_serial: true
  #       language: system

  # Security analysis to prevent sensitive data leakage
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.24.2
    hooks:
      - id: gitleaks
